name: e2e_test
description: Simple program to test if an error is transferred to Sentry.io
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  sentry:
    path:
      ./../dart
  http: '>=0.13.0 <=1.2.1'

dev_dependencies:
  lints: '>=2.0.0 <4.0.0'
