name: e2e_test
description: Simple program to test if an error is transferred to Sentry.io
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  sentry:
    path:
      ./../dart
  http: ^0.13.0

dev_dependencies:
  lints: ^2.0.0
