name: sentry_dio
description: An integration which adds support for performance tracing for the Dio package.
version: 6.6.0-alpha.1
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  sentry: ^6.6.0-alpha.1
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.2
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  coverage: ^1.2.0
  mockito: ^5.1.0
  http: ^0.13.4

dependency_overrides:
  sentry:
    path: ../dart
