name: sentry_dio
description: An integration which adds support for performance tracing for the Dio package.
version: 6.18.1
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/performance/instrumentation/automatic-instrumentation/#dio-http-library-instrumentation

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  sentry: 6.18.1

dev_dependencies:
  meta: ^1.3.0
  lints: ^2.0.0
  test: ^1.21.1
  coverage: ^1.3.0
  mockito: ^5.1.0
