name: microbenchmarks
description: Microbenchmarks
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0
  test: ^1.21.1
  benchmarking: ^0.6.1
  sentry_flutter:
    path: ../
  jni: ^0.14.0

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
