name: example
description: A simple command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  sentry:
    path: ../../dart
  uuid: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
