name: sentry_supabase
description: "Sentry integration to instrument Supabase."
version: 9.9.0
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  http: ^1.3.0
  sentry: 9.9.0

dev_dependencies:
  supabase: ^2.6.0
  lints: ^5.0.0
  test: ^1.24.0
