name: sentry
version: 4.0.0
description: >
  A crash reporting library for Dart that sends crash reports to Sentry.io.
  This library supports Dart Native, and Flutter for mobile, web, and desktop.
homepage: https://github.com/getsentry/sentry-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http: ">=0.11.0 <2.0.0"
  meta: ">=1.0.0 <2.0.0"
  stack_trace: ">=1.0.0 <2.0.0"
  uuid: "^2.2.2"

dev_dependencies:
  mockito: ">=2.0.0 <4.0.0"
  pedantic: ">=1.8.0 <2.0.0"
  test: ">=0.12.0 <2.0.0"
  yaml: ">=2.1.0 <3.0.0"
  test_coverage: ^0.4.2
