name: sentry
version: 4.0.7
description: >
  A crash reporting library for Dart that sends crash reports to Sentry.io.
  This library supports Dart VM and Web. For Flutter consider sentry_flutter instead.
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.0.0
  stack_trace: ^1.0.0
  uuid: ^2.0.0

dev_dependencies:
  mockito: ^4.1.3
  pedantic: ^1.9.2
  test: ^1.15.7
  yaml: ^2.2.1 # needed for version match (code and pubspec)
  collection: ^1.14.13
  coverage: ^0.14.2
