name: sentry_logging
description: An integration which adds support for recording log from the logging package.
version: 7.0.0-rc.2
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/configuration/integrations/logging/

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  logging: ^1.0.0
  sentry: 7.0.0-rc.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  coverage: ^1.3.0
  meta: ^1.3.0
