name: sentry_logging
description: An integration which adds support for recording log from the logging package.
version: 6.3.0-beta.4
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  sentry: ^6.3.0-beta.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  coverage: ^1.0.3

dependency_overrides:
  sentry:
    path: ../dart
