name: sentry_drift
description: An integration which adds support for performance tracing for the drift package.
version: 7.12.0
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  sentry: 7.12.0
  meta: ^1.3.0

  drift: ^2.13.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
  coverage: ^1.3.0
  mockito: ^5.1.0
  build_runner: ^2.4.6
  drift_dev: ^2.13.0
  yaml: ^3.1.0 # needed for version match (code and pubspec)
