name: sentry_drift
description: An integration which adds support for performance tracing for the drift package.
version: 8.4.0-beta.1
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  sentry: 8.4.0-beta.1
  meta: ^1.3.0
  drift: ^2.13.0

dev_dependencies:
  lints: ^3.0.0
  flutter_test:
    sdk: flutter
  coverage: ^1.3.0
  mockito: ^5.1.0
  build_runner: ^2.4.6
  drift_dev: ^2.13.0
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.1.0
  archive: ^3.1.2