name: sentry_isar
description: An integration which adds support for performance tracing for the isar package.
version: 9.11.0-beta.2
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0 # contains Isar Core
  sentry: 9.11.0-beta.2
  meta: ^1.3.0
  path: ^1.8.3

dev_dependencies:
  _sentry_testing:
    path: ../_sentry_testing
  isar_generator: ^3.1.0
  build_runner: ^2.4.6
  lints: '>=2.0.0'
  flutter_test:
    sdk: flutter
  coverage: ^1.3.0
  mockito: ^5.1.0
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  path_provider: ^2.1.1
