name: sentry_file
description: An integration which adds support for performance tracing for dart.io.File.
version: 8.9.0
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/configuration/integrations/file/

environment:
  sdk: '>=2.19.0 <4.0.0'

platforms:
  android:
  ios:
  macos:
  linux:
  windows:

dependencies:
  sentry: 8.9.0
  meta: ^1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.1
  coverage: ^1.3.0
  mockito: ^5.1.0
  yaml: ^3.1.0 # needed for version match (code and pubspec)
