name: sentry_file
description: An integration which adds support for performance tracing for dart.io.File.
version: 6.18.1
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/configuration/integrations/file

environment:
  # <2.19 because of https://github.com/dart-lang/sdk/issues/49647 breaking change
  sdk: '>=2.12.0 <2.19.0'

dependencies:
  sentry: 6.18.1
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
  coverage: ^1.3.0
  mockito: ^5.1.0
