name: sentry_sqflite
description: An integration which adds support for performance tracing for the sqflite package.
version: 8.9.0
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.3.0' # matching sqflite

platforms:
  android:
  ios:
  macos:

dependencies:
  sentry: 8.9.0
  sqflite: ^2.2.8
  sqflite_common: ^2.0.0
  meta: ^1.3.0
  path: ^1.8.3

dev_dependencies:
  lints: ^4.0.0
  flutter_test:
    sdk: flutter
  coverage: ^1.3.0
  mockito: ^5.1.0
  build_runner: ^2.4.2
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  sqflite_common_ffi: ^2.0.0
