name: sentry_dio
description: An integration which adds support for performance tracing for the Dio package.
version: 9.11.0-beta.2
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/integrations/dio/

environment:
  sdk: '>=3.5.0 <4.0.0'

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  dio: ^5.2.0
  sentry: 9.11.0-beta.2

dev_dependencies:
  meta: ^1.3.0
  lints: '>=2.0.0'
  test: ^1.21.1
  coverage: ^1.3.0
  mockito: ^5.1.0
  yaml: ^3.1.0 # needed for version match (code and pubspec)
