name: sentry_hive
description: An integration which adds support for performance tracing for the hive package.
version: 8.4.0-beta.1
homepage: https://docs.sentry.io/platforms/flutter/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  sentry: 8.4.0-beta.1
  hive: ^2.2.3
  meta: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  mockito: ^5.1.0
  build_runner: ^2.4.2
  coverage: ^1.3.0
