name: sentry_logging
description: An integration which adds support for recording log from the logging package.
version: 9.9.0
homepage: https://docs.sentry.io/platforms/dart/
repository: https://github.com/getsentry/sentry-dart
issue_tracker: https://github.com/getsentry/sentry-dart/issues
documentation: https://docs.sentry.io/platforms/dart/integrations/logging/

environment:
  sdk: '>=3.5.0 <4.0.0'

platforms:
  android:
  ios:
  macos:
  linux:
  windows:
  web:

dependencies:
  logging: ^1.0.0
  sentry: 9.9.0
  meta: ^1.3.0

dev_dependencies:
  lints: '>=2.0.0'
  test: ^1.21.1
  yaml: ^3.1.0 # needed for version match (code and pubspec)
  coverage: ^1.3.0
