name: sentry_dart_web_example
description: An absolute bare-bones web app.

publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  sentry:
    path: ../../dart/
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.2
  build_web_compilers: ^4.0.3
  lints: ^2.0.0
  webdev: ^3.0.4
