name: e2e-sentry-dart
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
    paths-ignore:
      - 'logging/**'
      - 'dio/**'
      - 'flutter/**'

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_DIST: 1

jobs:
  build:
    name: E2E
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ./e2e_test
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta]
    steps:
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d # pin@v1
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/checkout@v3
      - name: Run
        if: env.SENTRY_AUTH_TOKEN != null
        run: |
          dart pub get
          dart run --define=SENTRY_ENVIRONMENT=e2e

  analyze:
    uses: ./.github/workflows/analyze.yml
    with:
      package: e2e_test
      panaThreshold: 0 
